=== juanmalonso/apfcore/json/data/objects/models/users-model.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "maxLength": 50,
      "pattern": "^[a-z]{3,20}$"
    },
    "type": {
      "type": "string",
      "enum": [
        "OBJECT",
        "RELATION",
        "COLLECTION"
      ]
    },
    "idStrategy": {
      "type": "string",
      "enum": [
        "UUID",
        "SLUG",
        "CUSTOM",
        "SLUGPREFIX",
        "AUTOINCREMENT",
        "BASE36"
      ]
    },
    "partitionMode": {
      "type": "string",
      "enum": [
        "NONE",
        "Y4",
        "Y12",
        "Y53",
        "Y122"
      ]
    },
    "indexOptions": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "index": {
          "type": "string",
          "maxLength": 50,
          "pattern": "^[a-z]{3,20}$"
        },
        "indexable": {
          "type": "boolean",
          "default": true
        },
        "analysis": {
          "type": "object"
        },
        "basemapping": {
          "type": "object"
        }
      }
    },
    "uiOptions": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "maxLength": 50
        },
        "pluralName": {
          "type": "string",
          "maxLength": 50
        },
        "description": {
          "type": "string",
          "maxLength": 255
        },
        "icon": {
          "type": "string",
          "default": "caret right"
        },
        "help": {
          "type": "string",
          "maxLength": 255
        },
        "manageAs": {
          "type": "string",
          "enum": [
            "LIST",
            "GALLERY"
          ]
        }
      }
    },
    "fields": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "dataType",
          "order",
          "uiOptions",
          "indexOptions"
        ],
        "properties": {
          "id": {
            "type": "string",
            "maxLength": 50,
            "pattern": "^[a-z]{3,20}$"
          },
          "dataType": {
            "type": "string",
            "enum": [
              "boolean",
              "bainary",
              "datetime",
              "integer",
              "json",
              "objectr",
              "objectsr",
              "options",
              "password",
              "tags",
              "text",
              "textarea"
            ]
          },
          "defaultValue": {
            "type": "string"
          },
          "order": {
            "type": "integer"
          },
          "uiOptions": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "label": {
                "type": "string",
                "maxLength": 50
              },
              "info": {
                "type": "string"
              },
              "icon": {
                "type": "string",
                "default": "caret right"
              },
              "help": {
                "type": "string",
                "maxLength": 255
              },
              "hidden": {
                "type": "boolean",
                "default": false
              },
              "listable": {
                "type": "boolean",
                "default": true
              },
              "readOnly": {
                "type": "boolean",
                "default": false
              },
              "required": {
                "type": "boolean",
                "default": true
              },
              "sortable": {
                "type": "boolean",
                "default": false
              },
              "filterable": {
                "type": "boolean",
                "default": false
              },
              "searchable": {
                "type": "boolean",
                "default": false
              }
            }
          },
          "indexOptions": {
            "type": "object",
            "required": [
              "indexable"
            ],
            "properties": {
              "indexable": {
                "type": "boolean",
                "default": false
              },
              "mapping": {
                "type": "object",
                "required": [
                  "type"
                ],
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "text",
                      "keyword",
                      "date",
                      "long",
                      "double",
                      "boolean",
                      "ip",
                      "object",
                      "nested",
                      "geo_point",
                      "geo_shape",
                      "completion"
                    ]
                  }
                },
                "allOf": [
                  {
                    "if": {
                      "properties": {
                        "type": {
                          "const": "object"
                        }
                      }
                    },
                    "then": {
                      "properties": {
                        "dinamic": {
                          "type": "boolean",
                          "default": true
                        },
                        "properties": {
                          "type": "object"
                        }
                      }
                    }
                  },
                  {
                    "if": {
                      "properties": {
                        "type": {
                          "const": "date"
                        }
                      }
                    },
                    "then": {
                      "properties": {
                        "format": {
                          "type": "string",
                          "default": "yyyy-MM-dd HH:mm:ss",
                          "enum": [
                            "yyyy-MM-dd",
                            "yyyy-MM-dd HH:mm:ss",
                            "HH:mm:ss"
                          ]
                        }
                      }
                    }
                  }
                ]
              }
            }
          },
          "typeOptions": {
            "type": "object"
          },
          "validationOptions": {
            "type": "object"
          },
          "fileOptions": {
            "type": "object"
          }
        }
      }
    }
  }
}

=== juanmalonso/apfcore/json/data/objects/models/users-model.json
{
  "id": "users",
  "type": "OBJECT",
  "idStrategy": "AUTOINCREMENT",
  "partitionMode": "NONE",
  "indexOptions": {
    "index": "users",
    "indexable": true,
    "analysis": {},
    "basemapping": {}
  },
  "uiOptions": {
    "name": "Usuario",
    "pluralName": "Usuarios",
    "description": "Usuarios del Sistema",
    "icon": "caret right",
    "help": "",
    "manageAs": "LIST"
  },
  "fields": [
    {
      "id": "first_name",
      "dataType": "text",
      "defaultValue": "",
      "order": 1,
      "uiOptions": {
        "label": "Nombre",
        "info": "",
        "icon": "caret right",
        "help": "",
        "hidden": false,
        "listable": true,
        "readOnly": false,
        "required": true,
        "sortable": true,
        "filterable": false,
        "searchable": true
      },
      "indexOptions": {
        "indexable": true,
        "mapping": {
          "type": "text"
        }
      }
    },
    {
      "id": "last_name",
      "dataType": "text",
      "defaultValue": "",
      "order": 2,
      "uiOptions": {
        "label": "Apellidos",
        "info": "",
        "icon": "caret right",
        "help": "",
        "hidden": false,
        "listable": true,
        "readOnly": false,
        "required": true,
        "sortable": true,
        "filterable": false,
        "searchable": true
      },
      "indexOptions": {
        "indexable": true,
        "mapping": {
          "type": "text"
        }
      }
    },
    {
      "id": "email",
      "dataType": "text",
      "defaultValue": "",
      "order": 3,
      "uiOptions": {
        "label": "eMmail",
        "info": "",
        "icon": "caret right",
        "help": "",
        "hidden": false,
        "listable": true,
        "readOnly": false,
        "required": false,
        "sortable": false,
        "filterable": false,
        "searchable": true
      },
      "indexOptions": {
        "indexable": true,
        "mapping": {
          "type": "keyword"
        }
      }
    }
  ]
}
